spring:

  jpa:
    show-sql: false
    hibernate:
      #Switching
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false

  profiles:
    include: oauth


##Switching
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:./testDB;AUTO_SERVER=TRUE
      username: sa

server:
  port: 8081